### ISSUE TITLE
worklog-of-my-first-Pull-Request

### ISSUE THREAD

**Issue by masayuki14** [masayuki14/rabbit#1]
https://github.com/oss-gate/workshop/issues/288
Oss−Gate-Workshop でやったみたいなログをのこす。

Issueはこれ。
https://github.com/rabbit-shocker/rabbit/issues/104

**Comment by masayuki14** [comment]
http://rabbit-shocker.org/ のソースがリポジトリの `doc/` にあるとのことなのでForkしよう。

でもこれはコミッタの人から直接聞いたからわかったことであって、自分ひとりだとたどり着けないか、だいぶいろいろ試行錯誤をしないといけないだろうな。
😞

**Comment by masayuki14** [comment]
リポジトリをForkする。 
https://github.com/rabbit-shocker/rabbit

すでにフォークしてるんだけどね 😅

**Comment by masayuki14** [comment]
`doc/` の下を眺めてみよう。
Finderとクイックルックでいろいろ眺める。
静的ファイルがあるわけではなく、なんらかのWebフレームワークが使われてそうだ。

**Comment by masayuki14** [comment]
英語のページもあるんだね。これも対象だな。

**Comment by masayuki14** [comment]
対象ぺーじのURLはこれ。
http://rabbit-shocker.org/ja/usage/rabbit.html

同じパスをたどる。
はっけーん  :smile: :laughing: 
https://github.com/masayuki14/rabbit/blob/master/doc/ja/usage/rabbit.rd

**Comment by masayuki14** [comment]
`.rd` だからこれもRD形式のマークアップということなのかな？ :confused:
http://rabbit-shocker.org/ja/rd.html

**Comment by masayuki14** [comment]
さて。どうやってビルドするんだろうか。
Gemfileをみてみる。

```sh
% cat Gemfile
# -*- ruby -*-

source "https://rubygems.org"

gemspec
```

うーん。なんだろう・・・:confused:

**Comment by masayuki14** [comment]
とりあえず `bundle install` してみよう。

```sh
$  bundle install --path vendor/bundle
```

**Comment by masayuki14** [comment]
インストールはけっこう時間かりそうなのでその間に
`gemspec` について調べる。

`gemspec` で検索していくつかサイトをながめる。
- [gemspecとGemfileの役割をはっきりさせておく](http://sanemat.github.io/archives/langturn.com-translations-33/)

**Comment by masayuki14** [comment]
`rabbit.gemspec` ってファイルがあるからこれが関係あんのかな :sunglasses:❓

**Comment by masayuki14** [comment]
> アプリケーションの開発ではGemfile.lockをチェックインすべきです。 このファイルには使用するgemの正確なバージョンと場所が書かれています。 これはアプリケーション開発では望ましいことですが、Gem開発では嬉しくありません。
 [gemspecとGemfileの役割をはっきりさせておく](http://sanemat.github.io/archives/langturn.com-translations-33/)

なんか分かった気にはなった :smiling_imp:

**Comment by masayuki14** [comment]
はっ！ @kou さんはショッカーが好きなのか？
rabbit-shocker だしアイコンショッカーだし:smirk:

**Comment by masayuki14** [comment]
作業にもどろう。
たぶん [Rakefile](https://github.com/masayuki14/rabbit/blob/master/Rakefile) みたらなんかわかるだろう。
当たりをつける。

**Comment by masayuki14** [comment]
> namespace :doc do

あやしい。

Rakeはあんまりわからんから調べる。
[rake namespace](https://www.google.co.jp/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#safe=active&q=rake+namespace&*)で検索。
[RubyによるビルドツールRakeの覚え書き - Biglobe](http://www2s.biglobe.ne.jp/~idesaku/sss/tech/rake/) をみる。

`man rake` もあわせてチェック。
タスクの一覧を確認しよう。

``` sh
$ bundle exec rake -T
〜略
rake doc:server                    # Run documentation server
〜略
```

これだ！！ ⭐️ ⭐️ ⭐️

**Comment by masayuki14** [comment]
ドキドキ :heartbeat: ドキドキ :revolving_hearts:

```sh
$ bundle exec rake doc:server
```

**Comment by masayuki14** [comment]
キターーーーーーーーーーーーーーーーーーーーーーーーーーーー
http://localhost:4000/ja/usage/rabbit.html

**Comment by masayuki14** [comment]
RDの文法はまだちゃんと見てないけど他のとこ見たり雰囲気で編集する。

*before*
![2017-02-27 22 35 51](https://cloud.githubusercontent.com/assets/2756405/23363289/50965df2-fd3d-11e6-8225-64e78db7a2fa.png)

*after*
![2017-02-27 22 36 36](https://cloud.githubusercontent.com/assets/2756405/23363298/5cdb8042-fd3d-11e6-8a51-6c491783783d.png)

**Comment by masayuki14** [comment]
うん。良いんじゃないか。

**Comment by masayuki14** [comment]
ブランチを作る。
コミットログをみてコミットコメントの感じとかブランチの命名とかをチェックする。

```sh
$ git co -b feature/issue-104-improve-usage-doc
```

とした。

**Comment by masayuki14** [comment]
`ja/` の日本語ページ, `en/` の英語ページを編集してコミットする。
コミットコメントは英語なのでむかしブックマークした
http://anond.hatelabo.jp/20160725092419
を参考にコミットコメントを書く。

**Comment by masayuki14** [comment]
リポジトリに `push`

```sh
$  git push --set-upstream origin feature/issue-104-improve-usage-doc
Counting objects: 12, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (12/12), done.
Writing objects: 100% (12/12), 4.92 KiB | 0 bytes/s, done.
Total 12 (delta 9), reused 0 (delta 0)
remote: Resolving deltas: 100% (9/9), completed with 7 local objects.
To ssh://github.com/masayuki14/rabbit.git
 * [new branch]        feature/issue-104-improve-usage-doc -> feature/issue-104-improve-usage-doc
Branch feature/issue-104-improve-usage-doc set up to track remote branch feature/issue-104-improve-usage-doc from origin.
```

**Comment by masayuki14** [comment]
よっしゃこれでプルリクだせそう。

**Comment by masayuki14** [comment]
既存のプルリクを簡単にチェック。
日本語でもOKだけど、英語にしてみよう。

**Comment by masayuki14** [comment]
https://github.com/rabbit-shocker/rabbit/pull/105

出した :laughing: :clap:

**Comment by kou** [comment]
> でもこれはコミッタの人から直接聞いたからわかったことであって、自分ひとりだとたどり着けないか、だいぶいろいろ試行錯誤をしないといけないだろうな。

これは…フィードバックチャンス…！

**Comment by masayuki14** [comment]
> これは…フィードバックチャンス…！

そうなんですよね。
あと `$ rake doc:server`  ここも。

**Comment by masayuki14** [comment]
Merged pull request !!
